### ISSUE TITLE
CORS Issue on validation page

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Marketplace.Issues#58] opened 2023-09-04 08:29 UTC
Hi,

It looks like there is a CORS issue on the validators page:

https://marketplace.umbraco.com/validate

![image](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/9937803/59b78bf4-0eee-47bd-908b-686a7f57cc71)

**Comment by nathanwoulfe** [comment] 2023-09-05 02:45
Hey @AaronSadlerUK, thanks for letting us know - I've found the cause and have a fix on dev, just needs to be pushed though to live. Given that will likely happen before you read this, I'll close the issue now too. Thanks again.

**Closed as completed by nathanwoulfe** 2023-09-05 02:45 UTC
