### ISSUE TITLE
No packages showing in Safari (iOS & macOS)

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco.Marketplace.Issues#54] opened 2023-07-29 13:29 UTC
Currently (July 29, 2023) the Marketplace pages doesn't show any of the (presumably) fetched-as-JSON content:

![marketplace-missing-content](https://github.com/umbraco/Umbraco.Marketplace.Issues/assets/5463/35ccc6c0-d1ce-48db-b426-11119bc3cabc)

This is true for Safari in both **iOS** (`v16.5.1`) and **macOS** (`13.4.1` *Ventura*).

Essentially the same as #26 but with no console errors... and clicking the categories doesn't help either.

**Comment by nathanwoulfe** [comment] 2023-07-31 02:05
Hey @greystate, thanks for raising - I'll need to find a Mac machine/user to test with. Something related to fetching the cards as categories are also provided by the same API, so it's not entirely broken... Will check what was changed in the last release and try to work backwards...

Might be calling on you for verifying on dev once I've tracked down the cause.

**Comment by nathanwoulfe** [comment] 2023-08-01 03:42
@greystate I believe this is fixed now - same solution as #26, where a fresh deployment with new bundles resolves the issue. Obviously something goes amiss occasionally with bundle generation, just odd this time to have zero errors.

**Closed as completed by nathanwoulfe** 2023-08-01 03:42 UTC

**Comment by greystate** [comment] 2023-08-01 06:21
@nathanwoulfe Can confirm the page works for me again now in Safari on macOS + iOS 🙌
